# This file contains the configuration for the about (/about) page.

# Everything in this file is listen in chronological order to how they appear on the page.
# Both HTML and Markdown are supported in most values.

# Sections of the page to display. Each section gets its own item in the table of contents at the top.
sections:

  - id: "about" # This id is used for the table of contents, and for linking to the section. For example, this would be /about#2022-2023
    title: "Our Team" # The title of the section, displayed in the table of contents.
    content: "!file ./content/about.md" # The content of the section. Use !file [file path] to load data from another file relative to the location of this file