links: 
  github: "https://google.com"
  instagram: "https://instagram.com"
  twitter: "https://twitter.com"
  facebook: "https://facebook.com"
  youtube: "https://youtube.com"
  blueAlliance: "https://discord.com"
  email: "mailto:"