# This file contains the configuration for the home (default path) page.

# Everything in this file is listen in chronological order to how they appear on the page.
# Both HTML and Markdown are supported in most values.

# The large text at the top of the page.
title: 'RoboRaiders 3681'

# The text below the title.
about: >
  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sed sapien quam. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nullam sodales vitae risus ut mollis. Maecenas ultricies tellus ac quam hendrerit, quis dictum urna congue. Curabitur molestie molestie arcu nec elementum. Nullam sit amet massa interdum, luctus sem sed, maximus mauris. Maecenas aliquet laoreet risus, eget tempus diam venenatis a. Donec aliquam, erat at congue laoreet, enim neque auctor mauris, ac interdum turpis ipsum id lacus.

# The pictures in the image carousel.
#  The description is shown when the user hovers over the image.
#  The url is the file path relative to the 'public' folder.
pictures:
  - desc: 'Picture description'
    url: '/imgs/picture.png'

plz_donate: >
  As a student-run team, we rely on donations and sponsors to run. If you would like to donate, please click [here](%donation_link%).
